In [16]:
import pandas as pd

In [18]:
df = pd.read_csv('test.csv', delimiter=';')
df.head()

,Nome,CNS,Cross,Exame,DT,telefone,Mensagem
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Souza de lima Sortez,2.742390e+13,3.284724e+09,ABD TOTAL,03/08/2005,1.191187e+10,"ola, segue para mais infoemacoes da data e do ..."
2,juarez de formas da Silva,2.742390e+13,3.284724e+09,ABD TOTAL,04/08/2005,1.196187e+10,"ola, segue para mais infoemacoes da data e do ..."
3,Maria da Silva,2.742390e+13,3.284724e+09,ABD TOTAL,NaN,1.196187e+10,"ola, segue para mais infoemacoes da data e do ..."
4,julia de souza,2.742390e+13,NaN,ABD TOTAL,05/08/2005,1.196187e+10,"ola, segue para mais infoemacoes da data e do ..."

In [20]:
# Remove pontos e notação científica convertendo para inteiros
df['CNS'] = df['CNS'].astype(float).apply(lambda x: '{:.0f}'.format(x))
df['Cross'] = df['Cross'].astype(float).apply(lambda x: '{:.0f}'.format(x))
df['telefone'] = df['telefone'].apply(lambda x: f'+{x}' if not str(x).startswith('+') else str(x))
df.columns = df.columns.str.strip()

In [24]:
df.dropna(inplace=True)
df.head()

,Nome,CNS,Cross,Exame,DT,telefone,Mensagem
1,Souza de lima Sortez,27423897492834,3284723984,ABD TOTAL,03/08/2005,+11911873425.0,"ola, segue para mais infoemacoes da data e do ..."
2,juarez de formas da Silva,27423897492834,3284723984,ABD TOTAL,04/08/2005,+11961873425.0,"ola, segue para mais infoemacoes da data e do ..."
4,julia de souza,27423897492834,nan,ABD TOTAL,05/08/2005,+11961873425.0,"ola, segue para mais infoemacoes da data e do ..."

In [28]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time
import urllib.parse
import pandas as pd

# Abre o navegador e acessa o WhatsApp Web
navegador = webdriver.Chrome()
navegador.get('https://web.whatsapp.com/')

# Espera o carregamento do WhatsApp
while len(navegador.find_elements(By.ID, 'side')) < 1:
    time.sleep(1)

# Limpa colunas e índice
df.columns = df.columns.str.strip()
df.reset_index(drop=True, inplace=True)

# Corrige números de telefone (evita erro float)
df['telefone'] = df['telefone'].astype(str).str.replace('.0', '', regex=False)

# Envia mensagens
for i, mensagem in enumerate(df['Mensagem']):
    nome = df.loc[i, 'Nome']
    telefone = df.loc[i, 'telefone']
    texto = urllib.parse.quote(f'Oi, {nome}! {mensagem}')
    link = f'https://web.whatsapp.com/send?phone={telefone}&text={texto}'
    navegador.get(link)

    # Espera a conversa carregar
    while len(navegador.find_elements(By.XPATH, '//*[@id="main"]/footer/div[1]/div/span/div/div[2]/div[1]/div[2]/div[1]/p')) < 1:
        time.sleep(1)

    time.sleep(2)

    # Envia a mensagem
    campo = navegador.find_element(By.XPATH, '//*[@id="main"]/footer/div[1]/div/span/div/div[2]/div[1]/div[2]/div[1]/p')
    campo.send_keys(Keys.ENTER)

    time.sleep(10)

InvalidSessionIdException: Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: not connected to DevTools
  (Session info: chrome=135.0.7049.85)
Stacktrace:
	GetHandleVerifier [0x00007FF777945335+78597]
	GetHandleVerifier [0x00007FF777945390+78688]
	(No symbol) [0x00007FF7776F91AA]
	(No symbol) [0x00007FF7776E4EF5]
	(No symbol) [0x00007FF777709F04]
	(No symbol) [0x00007FF77777ED0F]
	(No symbol) [0x00007FF77779EBB2]
	(No symbol) [0x00007FF777776EC3]
	(No symbol) [0x00007FF7777403F8]
	(No symbol) [0x00007FF777741163]
	GetHandleVerifier [0x00007FF777BEEEED+2870973]
	GetHandleVerifier [0x00007FF777BE9698+2848360]
	GetHandleVerifier [0x00007FF777C06973+2967875]
	GetHandleVerifier [0x00007FF77796017A+188746]
	GetHandleVerifier [0x00007FF77796845F+222255]
	GetHandleVerifier [0x00007FF77794D2B4+111236]
	GetHandleVerifier [0x00007FF77794D462+111666]
	GetHandleVerifier [0x00007FF777933589+5465]
	BaseThreadInitThunk [0x00007FFB550BE8D7+23]
	RtlUserThreadStart [0x00007FFB56C114FC+44]